import path from 'node:path';
import { resolveOutputDir } from '../constants.js';
import { TOPIC_NAMES, renderWorkflowFile, workflowFileName } from '../topics/index.js';
import { ensureDir, writeFileSafe } from '../lib/fs.js';
import { info, warn } from '../lib/logger.js';

export async function runInit(options) {
  const outputDir = resolveOutputDir(options.path, options.outputDir);
  const workflowsDir = path.join(outputDir, 'workflows');

  await ensureDir(workflowsDir);

  for (const topicName of TOPIC_NAMES) {
    const targetFile = path.join(workflowsDir, workflowFileName(topicName));
    const result = await writeFileSafe(targetFile, renderWorkflowFile(topicName), options.force);
    if (result.written) {
      info(`created ${targetFile}`);
    } else {
      warn(`skipped ${targetFile} (already exists)`);
    }
  }

  const readmePath = path.join(outputDir, 'README.md');
  const readme = [
    '# Codex Flow Local Pack',
    '',
    'This directory is generated by Codex Flow CLI for Codex app.',
    'It contains workflow packs for .codex skill routing.',
    '',
    '## Included topics',
    '',
    ...TOPIC_NAMES.map((name) => `- ${name}`),
    ''
  ].join('\n');
  await writeFileSafe(readmePath, readme, options.force);
  info(`initialized Codex Flow in ${outputDir}`);
}
